#!/usr/bin/env bash

if [[ -n "$1" && $1 != "--" ]]; then
    answer=$(qalc +u8 -terse $1)
fi

# Path to menu application
if [ -z "${menu+1}" ]; then
    if [[ -n $(command -v dmenu) ]]; then
        menu="$(command -v dmenu)"
    else
        >&2 echo "Dmenu not found"
        exit
    fi
fi

while [[ $# -gt 0 && $1 != "--" ]]; do
    shift
done
[[ $1 == "--" ]] && shift

action=$(echo -e "Clear\nClose" | $menu "$@" -p " = ($answer)")

case $action in
    "Clear") $0 "--" "$@" ;;
    "Close") ;;
    "") ;;
    *) $0 "$answer $action" "--" "$@" ;;
esac
